#
FROM python:3.9

#
WORKDIR /app

#
COPY ./requirements_api.txt requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r requirements.txt

#
COPY ./api ./api
COPY ./model ./model
COPY ./data ./data

#
EXPOSE 80
CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80"]